- repo: local
  hooks:
    - id: lint-check-citation-space
      name: check citation punctuation
      description: Ensure that cite roles are preceeded by a space or backtick
      entry: '[^\s`]\{cite(?::\w+)?\}'
      language: pygrep
      types_or:
        - jupyter
        - markdown
- repo: 'https://github.com/pre-commit/pre-commit-hooks'
  rev: v4.3.0
  hooks:
    - id: check-added-large-files
