title: A search for molecular structure in oxygen-14 & interactive computing for nuclear laboratories
author: Angus Hollands
logo: content/image/uob-logo.svg
exclude_patterns:
  - .virtual_documents
  - node_modules
  - .direnv
execute:
  execute_notebooks: cache

bibtex_bibfiles:
  - references.bib
repository:
  url: 'https://github.com/agoose77/phd-thesis'
  path_to_book: docs
  branch: master
html:
  use_issues_button: true
  use_repository_button: true
  use_multitoc_numbering: false
latex:
  latex_engine: pdflatex
execute:
  stderr_output: remove-warn
sphinx:
  recursive_update: true
  local_extensions:
    policy: ./sphinx-ext
    # Hide any :dropdown: or {toggle} content for LaTeX
    hide_builder_classes: ./sphinx-ext
    load_mermaid: ./sphinx-ext
  extra_extensions:
    - sphinxcontrib.mermaid
    # Convert SVG to PDF
    - sphinxcontrib.rsvgconverter
    - sphinx_subfigure
  config:
    mermaid_version: null
    mermaid_init_js: 'mermaid.initialize({startOnLoad:true});'
    html_assets_policy: always
    builder_ignore_classes:
        latex: 
            - dropdown
            - toggle
            - margin
            - tag_no-latex
    mathjax3_config:
      loader:
        load:
          - '[tex]/physics'
      tex:
        packages: 
          '[+]':
            - physics
    latex_elements:
      preamble: |
        % Fix trace which is defined in JupyterBook.cls
        \let\trace\undefined
        \usepackage{physics}

        % Fix fragile hyperlinks in captions
        \usepackage{etoolbox}
        \AtBeginEnvironment{figure}{\pretocmd{\hyperlink}{\protect}{}{}}
        
        % Double line spacing
        \usepackage{setspace}
        \doublespacing
        
        \usepackage{placeins}
        \usepackage{afterpage}
        \afterpage{\FloatBarrier}
        
        \makeatletter
        \fancypagestyle{normal}{
            \fancyhf{}
            \fancyfoot[RO]{{\py@HeaderFamily\thepage}}
            \fancyfoot[LO]{{\py@HeaderFamily\nouppercase{\rightmark}}}
            \renewcommand{\footrulewidth}{0.4pt}
        }
        \makeatother

      tableofcontents: |
        \sphinxtableofcontents
        \listoffigures
        \listoftables
      
      sphinxsetup: "hmargin={1in,1in}, vmargin={0.7in,1in}, marginpar=1in"

    # MyST-nb support for image/svg+xml
    nb_mime_priority_overrides:
        - ["latex", "image/svg+xml", 15]
    nb_ipywidgets_js:
        # Load RequireJS, used by the IPywidgets for dependency management
        "https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js": 
            "integrity": "sha256-Ae2Vz/4ePdIu6ZyI/5ZGsYnb+m0JlOmKPjt6XZ9JJkA="
            "crossorigin": "anonymous"
        # Load IPywidgets bundle for embedding.
        "https://cdn.jsdelivr.net/npm/@jupyter-widgets/html-manager@*/dist/embed-amd.js":
            "data-jupyter-widgets-cdn": "https://cdn.jsdelivr.net/npm/"
            "crossorigin": "anonymous"
        
parse:
  myst_heading_anchors: 3
  myst_enable_extensions:
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - linkify
    - tasklist
