# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: PhD Thesis
author: Angus Hollands
logo: logo.png
exclude_patterns: 
  - .virtual_documents
  - generation




# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: cache


# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/agoose77/phd-thesis  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  use_multitoc_numbering: false

latex:
  latex_engine: pdflatex

sphinx:
  recursive_update: true
  local_extensions: 
      mermaid: ./ext
      policy: ./policy

  config:
      # Mermaid
      mermaid_version: latest
      mermaid_js_priority: 499
      mermaid_init_js: "mermaid.initialize({startOnLoad:true});"
      # Policy
      html_assets_policy: always

parse:
  myst_heading_anchors: 3
  myst_enable_extensions:  # default extensions to enable in the myst parser. See https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    # - html_admonition
    # - html_image
    - linkify
    # - replacements
    # - smartquotes
    # - substitution
    - tasklist
