title: A novel method for track fitting in TPCs, and interactive computing for nuclear laboratories
author: Angus Hollands
exclude_patterns:
  - .virtual_documents
  - node_modules
  - .direnv
  - README.md
  - extern/*
  - content/4000*.md
  - .build*

mystnb:
  execute_notebooks: cache

bibtex_bibfiles:
  - references.bib

repository:
  url: 'https://github.com/agoose77/phd-thesis'
  path_to_book: docs
  branch: master
html:
  use_issues_button: true
  use_repository_button: true
  use_multitoc_numbering: false
latex:
  latex_engine: pdflatex
  latex_documents:
    targetname: thesis.tex
execute:
  stderr_output: remove-warn
sphinx:
  recursive_update: true
  local_extensions:
    policy: ./sphinx-ext
    # Hide any :dropdown: or {toggle} content for LaTeX
    hide_builder_classes: ./sphinx-ext
    load_mermaid: ./sphinx-ext
    caption_after_table: ./sphinx-ext
  extra_extensions:
    - sphinxcontrib.mermaid
    # Convert SVG to PDF
    - sphinxcontrib.rsvgconverter
    - sphinx_subfigure
  config:
    html_theme_options:
      logo:
        image_light: content/image/uob-logo.svg
        image_dark: content/image/uob-logo-reversed.svg
    latex_logo: content/image/uob-logo.pdf
    mermaid_version: ""
    mermaid_init_js: 'mermaid.initialize({startOnLoad:true});'
    mermaid_pdfcrop: pdfcrop
    html_assets_policy: always
    builder_ignore_classes:
        latex: 
            - dropdown
            - toggle
            - margin
            - tag_no-latex
            - no-latex
    mathjax3_config:
      loader:
        load:
          - '[tex]/physics'
      tex:
        packages: 
          '[+]':
            - physics
    math_number_all: true
    math_eqref_format: "Eqn. {number}"
    suppress_warnings: 
      - mystnb.eval
    latex_elements:
      preamble: |
        % Fix trace which is defined in JupyterBook.cls
        \let\trace\undefined
        \usepackage{physics}

        % % Hide links for printing
        % \hypersetup{
        %     hidelinks
        % }
        
        % Fix fragile hyperlinks in captions
        \usepackage{etoolbox}
        \AtBeginEnvironment{figure}{\pretocmd{\hyperlink}{\protect}{}{}}
        
        % Remove intrinsic bib name
        \patchcmd{\thebibliography}{\chapter*{\bibname}}{}{}{}
        
        % Double line spacing
        \usepackage{setspace}
        \doublespacing

        % Clear floats between sections
        \usepackage[section]{placeins}
        % \usepackage{afterpage}
        % \afterpage{\FloatBarrier}

        % Simplify headings
        \makeatletter
        \fancypagestyle{normal}{
            \fancyhf{}
            \fancyfoot[RO]{{\py@HeaderFamily\thepage}}
            \fancyfoot[LO]{{\py@HeaderFamily\nouppercase{\rightmark}}}
            \renewcommand{\footrulewidth}{0.4pt}
        }
        \makeatother

      tableofcontents: |
        \sphinxtableofcontents
        \listoffigures
        \listoftables
      
      sphinxsetup: "hmargin={1in,1in}, vmargin={0.7in,1in}, marginpar=1in"
      maketitle: |
        \makeatletter
        \let\sphinxrestorepageanchorsetting\relax
        \ifHy@pageanchor\def\sphinxrestorepageanchorsetting{\Hy@pageanchortrue}\fi
        \hypersetup{pageanchor=false}% avoid duplicate destination warnings
        \begin{titlepage}%
          \let\footnotesize\small
          \let\footnoterule\relax
          \noindent\rule{\textwidth}{1pt}\par
            \begingroup % for PDF information dictionary
             \def\endgraf{ }\def\and{\& }%
             \pdfstringdefDisableCommands{\def\\{, }}% overwrite hyperref setup
             \hypersetup{pdfauthor={\@author}, pdftitle={\@title}}%
            \endgroup
          \begin{flushright}%
            \sphinxlogo
            \py@HeaderFamily
            {\Huge \@title \par}
            \vfill
            {\LARGE By}
            \vfill
            {\LARGE
              \begin{tabular}[t]{c}
                \@author
                
              \end{tabular}\kern-\tabcolsep
              \par}
          \end{flushright}%\par
          \vfill
          \begin{flushleft}%
            \py@HeaderFamily
            {\large
              A thesis submitted to \\
              the University of Birmingham \\
              for the degree of \\
              {\LARGE Doctor of Philosophy}\\
              \par}
          \end{flushleft}%\par
          \begin{flushright}%\par
            \py@HeaderFamily
            \vfill
            {\large
              Nuclear Physics Group\\
              School of Physics and Astronomy\\
              College of Engineering and Physical Sciences\\
              University of Birmingham\\
             \@date \par
             \vfill
             \py@authoraddress \par
            }%
          \end{flushright}%\par
          \@thanks
        \end{titlepage}%
        \setcounter{footnote}{0}%
        \let\thanks\relax\let\maketitle\relax
        %\gdef\@thanks{}\gdef\@author{}\gdef\@title{}
        \clearpage
        \ifdefined\sphinxbackoftitlepage\sphinxbackoftitlepage\fi
        \if@openright\cleardoublepage\else\clearpage\fi
        \sphinxrestorepageanchorsetting
        \makeatother
    # MyST-nb support for image/svg+xml
    nb_execution_raise_on_error: true
    nb_eval_name_regex: ".*"
    nb_mime_priority_overrides:
        - ["latex", "image/svg+xml", 15]
    nb_ipywidgets_js:
        # Load RequireJS, used by the IPywidgets for dependency management
        "https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js": 
            "integrity": "sha256-Ae2Vz/4ePdIu6ZyI/5ZGsYnb+m0JlOmKPjt6XZ9JJkA="
            "crossorigin": "anonymous"
        # Load IPywidgets bundle for embedding.
        "https://cdn.jsdelivr.net/npm/@jupyter-widgets/html-manager@*/dist/embed-amd.js":
            "data-jupyter-widgets-cdn": "https://cdn.jsdelivr.net/npm/"
            "crossorigin": "anonymous"
        
parse:
  myst_heading_anchors: 3
  myst_enable_extensions:
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - linkify
    - tasklist
