title: PhD Thesis
author: Angus Hollands
logo: logo.png
exclude_patterns:
  - .virtual_documents
  - node_modules
execute:
  execute_notebooks: cache

bibtex_bibfiles:
  - references.bib
repository:
  url: 'https://github.com/agoose77/phd-thesis'
  path_to_book: docs
  branch: master
html:
  use_issues_button: true
  use_repository_button: true
  use_multitoc_numbering: false
latex:
  latex_engine: pdflatex
sphinx:
  recursive_update: true
  local_extensions:
    policy: ./sphinx-ext
    # Hide any :dropdown: or {toggle} content for LaTeX
    hide_dropdowns: ./sphinx-ext
    load_mermaid: ./sphinx-ext
  extra_extensions:
    - sphinxcontrib.mermaid
    # Convert SVG to PDF
    - sphinxcontrib.rsvgconverter
  config:
    mermaid_init_js: 'mermaid.initialize({startOnLoad:true});'
    html_assets_policy: always
    mathjax3_config:
      loader:
        load:
          - '[tex]/physics'
      tex:
        packages:
          '[+]':
            - physics
    latex_elements:
      preamble: |
        % Fix trace which is defined in JupyterBook.cls
        \let\trace\undefined
        \usepackage{physics}

        % Fix fragile hyperlinks in captions
        \usepackage{etoolbox}
        \AtBeginEnvironment{figure}{\pretocmd{\hyperlink}{\protect}{}{}}
        
        % Double line spacing
        \usepackage{setspace}
        \doublespacing

    # MyST-nb support for image/svg+xml
    nb_mime_priority_overrides:
        - ["latex", "image/svg+xml", 15]
parse:
  myst_heading_anchors: 3
  myst_enable_extensions:
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - linkify
    - tasklist
