[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Angus Hollands", email = "goosey15@gmail.com"},
]
dependencies = [
    "jupyterlab>=3.3.0a1",
    "jupyter-book>=0.12.1",
    "jupyterlab-markup>=1.0.1",
    "JLDracula>=0.1.0",
    "matplotlib>=3.5.1",
    "numpy>=1.22.1",
    "awkward>=1.7.0",
    "jupyterlab-myst>=0.1.3",
]
requires-python = ">=3.9"
license = {text = "MIT"}

[project.urls]
homepage = ""

[tool]
[tool.pdm]

[build-system]
requires = ["pdm-pep517"]
build-backend = "pdm.pep517.api"
