#!/usr/bin/env python
import argparse
import json
import pathlib
import unicodedata

def main(argv=None):
    parser = argparse.ArgumentParser()
    parser.add_argument("source", type=pathlib.Path, nargs="+")
    parser.add_argument("-c", "--cat", type=str, action="append")
    parser.add_argument("--json", action="store_true")
    args = parser.parse_args()

    categories = set(args.cat)

    symbols = set()
    for p in args.source:
        symbols |= {c for c in p.read_text() if unicodedata.category(c) in categories}

    if args.json:
        print(json.dumps(list(symbols)))
    else:
        print("".join(symbols))
    
if __name__ == "__main__":
    main()
